language: php

php:
  - 7.1
  - 7.2

install:
  - composer self-update || echo "[ERROR] update-composer failed!"
  - composer install --no-interaction --optimize-autoloader

before_script:
  - vendor/bin/phpcs --standard=vendor/damejidlo/coding-standard/DameJidloCodingStandard/ruleset.xml --extensions=php --encoding=utf-8  src/
  - vendor/bin/phpstan.phar analyse -l 2 -c phpstan.neon src tests

script:
  - ./vendor/bin/tester -p php -s -j 32 -c ./tests/php.ini ./tests

after_failure:
  - 'for i in $(find ./tests -name \*.log); do echo "--- $i"; cat $i; echo; echo; done'
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
